import { addIcons } from 'ionicons';
import {
  chevronForward,
  chevronBack,
  chevronForwardOutline,
  heart,
  heartOutline,
  volumeHigh,
  volumeMute,
  play,
  pause,
  playCircle,
  pauseCircle,
  stop,
  timeOutline,
  moonOutline,
  moon,
  sunny,
  settingsOutline,
  musicalNotesOutline,
  headsetOutline,
  trophyOutline,
  close,
  checkmark,
  checkmarkCircle,
  checkmarkOutline,
  contrastOutline,
  diamondOutline,
  diamond,
  refreshOutline,
  constructOutline,
  barChartOutline,
  lockClosed,
  bookmarkOutline,
  trashOutline,
  musicalNoteOutline,
  addCircleOutline,
  removeCircleOutline,
  addOutline,
  closeOutline,
  pulseOutline,
  bulbOutline,
  hourglassOutline,
} from 'ionicons/icons';

/**
 * Register all Ionicons used in the application
 * This ensures icons are available throughout the app in standalone mode
 */
export function registerIcons(): void {
  addIcons({
    'chevron-forward': chevronForward,
    'chevron-back': chevronBack,
    'chevron-forward-outline': chevronForwardOutline,
    heart,
    'heart-outline': heartOutline,
    'volume-high': volumeHigh,
    'volume-mute': volumeMute,
    play,
    pause,
    'play-circle': playCircle,
    'pause-circle': pauseCircle,
    stop,
    'time-outline': timeOutline,
    'moon-outline': moonOutline,
    moon,
    sunny,
    'settings-outline': settingsOutline,
    'musical-notes-outline': musicalNotesOutline,
    'headset-outline': headsetOutline,
    'trophy-outline': trophyOutline,
    'contrast-outline': contrastOutline,
    'diamond-outline': diamondOutline,
    diamond,
    'refresh-outline': refreshOutline,
    'construct-outline': constructOutline,
    'bar-chart-outline': barChartOutline,
    'lock-closed': lockClosed,
    'checkmark-circle': checkmarkCircle,
    'checkmark-outline': checkmarkOutline,
    'bookmark-outline': bookmarkOutline,
    'trash-outline': trashOutline,
    'musical-note-outline': musicalNoteOutline,
    'add-circle-outline': addCircleOutline,
    'remove-circle-outline': removeCircleOutline,
    'add-outline': addOutline,
    'close-outline': closeOutline,
    'pulse-outline': pulseOutline,
    'bulb-outline': bulbOutline,
    'hourglass-outline': hourglassOutline,
    close,
    checkmark,
  });
}

